"""What the main window's parts share: the attributes and methods one
module of StorageScannerApp uses from another.

StorageScannerApp (storage_scanner/app.py) is built from the mixins under
storage_scanner/ui/, and the windows it opens (DuplicatesWindow,
GrowthHistoryWindow, CleanupWindow, FileListWindow, TreemapPane) are handed
the app itself. An attribute set in one file and read in another, or a
method called across files, is declared here once, so mypy checks every use
of it: a misspelled name or a wrong argument count is a type error instead
of an AttributeError the first time that code path runs.

- A window's `app` parameter is annotated `AppState`.
- Every mixin derives from `AppMixin`: AppState while type checking, plain
  `object` at run time, so the declarations cost nothing when the app runs.
  AppState itself exists only while type checking (import it under
  `if TYPE_CHECKING:`).

AppState is a plain class, not a typing.Protocol, on purpose: a Protocol's
bare `name: type` members are abstract, and mypy lets each subclass's first
`self.name = value` redeclare them with the value's narrower type, so
`self.scan_thread = None` in one mixin and a Thread in another would leave
each file with its own, conflicting, idea of the attribute.

pyproject.toml has mypy check the bodies of the untyped functions under
storage_scanner/ui/ and app.py (check_untyped_defs), which is where every
one of these uses is.
"""

from typing import TYPE_CHECKING, Any, Callable, ClassVar, Optional

if TYPE_CHECKING:
    import queue
    import threading
    from collections.abc import Sequence
    from tkinter import BooleanVar, Menu, Misc, StringVar, Tk, ttk

    from storage_scanner.cart import CartManager
    from storage_scanner.delete_service import (
        DeletedSet,
        DeleteRequest,
        DeleteResult,
        DeleteService,
    )
    from storage_scanner.live_tree_model import RowDisplay
    from storage_scanner.models import FileNode, Node
    from storage_scanner.scan_progress import WalkTracker
    from storage_scanner.scan_progress_model import ProgressView, ScanProgressModel
    from storage_scanner.turbo_scan import ScanReport
    from storage_scanner.ui.treemap_pane import TreemapPane

    # duplicate_finder.find_duplicate_files' groups: (size, (edge digest,
    # middle digest), the copies), largest recoverable space first.
    DuplicateGroup = tuple[int, tuple, list[FileNode]]
    # live_tree's view state: the folders opened during a scan, the focused
    # row and the top visible row, as nodes the finished tree reuses.
    LiveViewState = tuple[list[Node], Optional[Node], Optional[Node]]

    class AppState:
        # -- Window and widgets (app.py, ui/main_window.py) -------------------- #
        root: Tk
        appearance: str  # appearance.LIGHT or appearance.DARK
        main_panes: ttk.PanedWindow
        tree: ttk.Treeview
        treemap_pane: TreemapPane
        menu: Menu  # the main tree's right-click menu
        status_var: StringVar
        progress: ttk.Progressbar
        _statusbar_frame: ttk.Frame
        _scan_details_frame: ttk.Frame
        changed_only_var: BooleanVar
        changed_only_check: ttk.Checkbutton

        # -- Toolbar (ui/toolbar.py) -------------------------------------------- #
        toolbar_frame: ttk.Frame
        path_var: StringVar
        scan_btn: ttk.Button
        cancel_btn: ttk.Button
        elevate_btn: ttk.Button
        tools_btn: ttk.Button
        top_count_var: StringVar
        top_count_combo: ttk.Combobox
        show_treemap_var: BooleanVar
        shade_treemap_var: BooleanVar
        turbo_scan_var: BooleanVar

        # -- The scan and its tree (app.py, ui/scan_lifecycle.py) --------------- #
        _initial_path: Optional[str]  # the folder named on the command line
        progress_q: queue.Queue[tuple]  # (kind, payload...) from the scan worker
        cancel_event: threading.Event
        scan_thread: Optional[threading.Thread]
        _scan_active: bool
        _history_thread: Optional[threading.Thread]
        root_node: Optional[Node]
        node_by_iid: dict[str, Node]
        _more_rows: dict[str, str]  # a level's "N more" row -> its parent row
        _heat_tags: set[str]
        _sort_key: str
        _sort_reverse: bool
        # {normalized folder path: size} from the scan saved before this one.
        _previous_folder_sizes: dict[str, int]
        _live_tracker: Optional[WalkTracker]
        # The first row's y (below the heading) and the row height, once found.
        _live_row_top: Optional[int]
        _live_row_height: Optional[int]
        _owners: dict[str, str]  # path -> owner, "" when it can't be read
        last_scan_id: Optional[int]
        last_previous_scan_id: Optional[int]
        last_growth_rows: list
        PHASE_SAVING_HISTORY: ClassVar[str]
        PHASE_WAITING_FOR_ELEVATED_SCAN: ClassVar[str]

        # -- Duplicates, the Cleanup Cart, deleting ----------------------------- #
        dup_progress_q: queue.Queue[tuple]
        dup_thread: Optional[threading.Thread]
        dup_cancel_event: threading.Event
        dup_stats: dict[str, int]
        duplicates: Optional[list[DuplicateGroup]]
        _duplicates_scan_root: Optional[Node]  # the tree `duplicates` is from
        cart: CartManager
        delete_service: DeleteService

        # -- ui/main_window.py -------------------------------------------------- #
        def _toggle_treemap(self) -> None: ...
        def _toggle_treemap_shading(self) -> None: ...
        def _reveal(self, path: str, is_dir: bool) -> None: ...
        def _open_in_explorer(self) -> None: ...

        # -- ui/main_tree.py ---------------------------------------------------- #
        def _heat_tag(self, fraction: float) -> str: ...
        def _insert_node(
            self, parent_iid: str, node: Node, parent_size: int, index: int = 0
        ) -> str: ...
        def _populate_children(self, parent_iid: str, node: Node) -> None: ...
        def _show_more_rows(self, more_iid: str) -> None: ...
        def _on_open(self, _event: object) -> None: ...
        def _on_double_click(self, _event: object) -> None: ...
        def _sort_by(self, key: str) -> None: ...
        def _update_heading_arrows(self) -> None: ...
        def _refresh_row(self, iid: str) -> None: ...
        def _folder_change(self, node: Node) -> Optional[int]: ...
        def _show_changes(self, previous_scan_id: Optional[int]) -> None: ...
        def _refilter_tree(self) -> None: ...
        def _select_in_tree(self, nodes: Sequence[Node]) -> None: ...
        def _remove_main_tree_row(self, iid: str) -> None: ...
        def _sort_level(self, parent_iid: str) -> None: ...

        # -- ui/owner_column.py ------------------------------------------------- #
        def _owner_reset(self) -> None: ...
        def _owner_watch(
            self, set_scrollbar: Callable[[float, float], object]
        ) -> Callable[[float, float], None]: ...
        def _known_owner(self, node: Node) -> Optional[str]: ...
        def _owner_row_added(self, iid: str, node: Node, path: str) -> None: ...
        def _owner_view_changed(self) -> None: ...
        def _want_all_owners(self) -> None: ...

        # -- ui/live_tree.py ---------------------------------------------------- #
        def _live_reset(self) -> None: ...
        def _live_bind(self, tree: ttk.Treeview, scrollbar: ttk.Scrollbar) -> None: ...
        def _first_visible_row(self) -> str: ...
        def _begin_scan_view(self, target: str) -> None: ...
        def _scan_running(self) -> bool: ...
        def _deleting_blocked(self) -> bool: ...
        def _refuse_delete_during_scan(self, parent: Optional[Misc] = None) -> bool: ...
        def _live_attach(self, tracker: WalkTracker) -> None: ...
        def _live_tick(self, view: Optional[ProgressView]) -> None: ...
        def _live_freeze(self) -> None: ...
        def _row_tags(self, display: RowDisplay, index: int) -> tuple[str, ...]: ...
        def _live_open(self, iid: str, node: Node) -> None: ...
        def _live_resort(self) -> None: ...
        def _live_view_state(self) -> Optional[LiveViewState]: ...
        def _restore_view_state(self, state: LiveViewState) -> None: ...

        # -- ui/toolbar.py, ui/scan_lifecycle.py -------------------------------- #
        def _refresh_tools_state(self) -> None: ...
        def start_scan(self) -> None: ...
        def cancel_scan(self) -> None: ...
        def _start_elevated_scan_headless(
            self,
            target: str,
            run_scan_fn: Callable[[str], tuple[bool, str]],
            waiting_suffix: str,
        ) -> None: ...
        def _start_determinate_progress(self, maximum: int) -> None: ...
        def _update_determinate_progress(self, value: int) -> None: ...
        def _stop_progress(self) -> None: ...

        # -- ui/scan_progress_panel.py, ui/scan_banners.py ---------------------- #
        def _scan_progress_start(self, target: str) -> None: ...
        def _scan_progress_message(self, kind: str, payload: Any) -> None: ...

        # Returns the current scan's model, the `token` for _scan_progress_end.
        def _scan_progress_phase(self, label: str) -> Optional[ScanProgressModel]: ...
        def _scan_progress_cancel_requested(self) -> None: ...
        def _scan_progress_end(
            self, outcome: str, token: Optional[ScanProgressModel] = None
        ) -> None: ...
        def _scan_progress_refresh(self) -> Optional[ProgressView]: ...
        def _show_scan_details(
            self, report: Optional[ScanReport], inaccessible_nodes: list
        ) -> None: ...
        def _hide_scan_details(self) -> None: ...
        def _show_turbo_fallback_banner(self, reason: str) -> None: ...
        def _dismiss_turbo_fallback_banner(self) -> None: ...
        def _show_inaccessible_paths_banner(self, inaccessible_nodes: list) -> None: ...
        def _dismiss_inaccessible_paths_banner(self) -> None: ...

        # -- ui/history_window.py, ui/budget_window.py -------------------------- #
        def _save_history_worker(
            self, node: Node, progress_token: Optional[ScanProgressModel]
        ) -> None: ...
        def _remove_scan(self, scan_path: str, scan_id: int, date_text: str) -> None: ...
        def show_growth_history(
            self, compare_a_id: Optional[int] = None, compare_b_id: Optional[int] = None
        ) -> None: ...
        def _show_budget_banner(self, breaches: list) -> None: ...

        # -- Deleting and the Cleanup Cart (ui/delete_dialogs.py, cart_window.py) #
        def _watch_deletions(self, win: Misc, listener: Callable[[DeletedSet], object]) -> None: ...
        def _delete_nodes(
            self,
            requests: Sequence[DeleteRequest],
            parent: Optional[Misc] = None,
            report: bool = True,
        ) -> list[DeleteResult]: ...
        def _refresh_cart_indicator(self) -> None: ...

        # -- Tools menu windows -------------------------------------------------- #
        def _find_duplicate_files(
            self,
            progress_q: Optional[queue.Queue[tuple]] = None,
            cancel_event: Optional[threading.Event] = None,
        ) -> list[DuplicateGroup]: ...
        def _add_data_tools_menu(self, tools_menu: Menu) -> None: ...
        def export_results(self) -> None: ...
        def show_schedule_scans(self) -> None: ...
        def show_audit_log(self) -> None: ...
        def show_budgets(self) -> None: ...
        def show_cart(self) -> None: ...
        def show_cleanup_recommendations(self) -> None: ...
        def show_duplicates(self) -> None: ...
        def show_top_files(self, count: Optional[int] = None) -> None: ...
        def show_file_types(self) -> None: ...
        def show_onboarding(self) -> None: ...
        def show_search_window(self) -> None: ...

    AppMixin = AppState
else:
    AppMixin = object
